# Generated by Django 6.0.5 on 2026-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/%d')),
                ('media_id', models.IntegerField(blank=True, null=True)),
                ('solution_id', models.IntegerField(blank=True, null=True)),
                ('report_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('full', 'Full'), ('part', 'Part')], default='part', max_length=20)),
            ],
        ),
    ]
